In [1]:
import numpy as np
import time

# 1. 파이썬 리스트를 사용한 경우
my_list = list(range(1_000_000))
start_time = time.time()
result_list = [x * 2 for x in my_list]
end_time = time.time()
print(f"파이썬 리스트 실행 시간: {end_time - start_time:.5f}초")


파이썬 리스트 실행 시간: 0.07141초


In [2]:
# 2. 넘파이 배열을 사용한 경우
my_array = np.arange(1_000_000)
start_time = time.time()
result_array = my_array * 2
end_time = time.time()
print(f"넘파이 배열 실행 시간: {end_time - start_time:.5f}초")


넘파이 배열 실행 시간: 0.00389초


In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
a = np.array([1, 2, 3, 4, 5])
# 배열의 모든 요소에 10 더하기
print(a + 10)
# 배열의 모든 요소에 2 곱하기
print(a * 2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [6]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
print(arr1+arr2)

[11 22 33]


In [7]:
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])

[20 30 40]


In [8]:
a = np.array([10, 20, 30, 40, 50])
# 배열 a의 요소 중 25보다 큰 값만 선택
condition_mask = (a > 25) # 1단계: 불리언 마스크 생성
filtered_array = a[condition_mask] # 2단계: 마스크를 사용해 데이터 필터링
print(filtered_array)

[30 40 50]


In [9]:
a = np.array([10, 20, 30, 40, 50])
print(a[a>25])

[30 40 50]


In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

(6,)
(2, 3)


In [11]:
# 6개의 요소를 가진 1차원 배열
arr1 = np.array([1, 2, 3, 4, 5, 6])
# arr1을 3행 2열의 2차원 배열로 변경
arr2 = arr1.reshape(3, 2)
print(arr2)


[[1 2]
 [3 4]
 [5 6]]


In [12]:
#실전예제
import numpy as np
# 비행 거리 배열 (단위: km)
distances = np.array([1, 2, 3, 5, 8])
# 각 비행 시 예상 풍속 배열 (단위: m/s)
windspeeds = np.array([0, 5, 10, 7, 12])

base_usage_rate = 10
additional_usage_rate = windspeeds

total_usage_rate = base_usage_rate + additional_usage_rate

battery_consumption = distances * total_usage_rate

print("비행 거리 (km):", distances)
print("풍속 (m/s):", windspeeds)
print("총 소모율 (%/km):", total_usage_rate)
print("예상 배터리 소모량 (%):", battery_consumption)

비행 거리 (km): [1 2 3 5 8]
풍속 (m/s): [ 0  5 10  7 12]
총 소모율 (%/km): [10 15 20 17 22]
예상 배터리 소모량 (%): [ 10  30  60  85 176]


In [13]:
import pandas as pd
student_data = {
'name': ['Kim', 'Lee', 'Park'],
'test': [85, 92, 78],
'assign1': [88, 95, 80],
'assign2': [91, 89, 82]
}
df = pd.DataFrame(student_data)
display(df)


name  test  assign1  assign2
0   Kim    85       88       91
1   Lee    92       95       89
2  Park    78       80       82

In [14]:
data_list = [
['Kim', 85, 88, 91],
['Lee', 92, 95, 89],
['Park', 78, 80, 82]
]
column_names = ['name', 'test', 'assign1', 'assign2']
df_from_list = pd.DataFrame(data_list, columns=column_names)
display(df_from_list)


name  test  assign1  assign2
0   Kim    85       88       91
1   Lee    92       95       89
2  Park    78       80       82

In [15]:
# 빈 데이터프레임 생성
df_empty = pd.DataFrame()
# 열 순차적으로 추가
df_empty['name'] = ['Kim', 'Lee', 'Park']
df_empty['test'] = [85, 92, 78]
df_empty['assign1'] = [88, 95, 80]
df_empty['assign2'] = [91, 89, 82]
display(df_empty)

name  test  assign1  assign2
0   Kim    85       88       91
1   Lee    92       95       89
2  Park    78       80       82

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [17]:
df = pd.read_csv('/content/drive/MyDrive/파이썬기초/Iris (1).csv')

In [18]:
df['Id']

0        1
1        2
2        3
3        4
4        5
      ... 
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64